Finalizado tagline,navbar, firstheading
Antoniomorales17/Building-a-website-collaborative pull request #11
Opened 2023-05-02 18:33 UTC by AlvaroMartinFernandez

2023-05-02 19:01 UTC, Antoniomorales17 approved these changes
ok

2023-05-02 19:02 UTC, Antoniomorales17 requested changes
ok

2023-05-17 17:37 UTC, Antoniomorales17 approved these changes
ok

2023-05-23 15:17 UTC, AlvaroMartinFernandez commented
Pull nuevo

2023-05-23 16:07 UTC, merged